### ISSUE TITLE
Config included behavior

### ISSUE THREAD

**Issue by igorkulman** [IBDecodable/IBLinter#81]
Running the tool with `.iblinter.yml`

```yml
disabled_rules:
  - custom_class_name
included:
  - Scenarios
```

The tool also accesses different locations that are outside the Scenarios folder, like the Carthage folder. I would expect the tool to only traverse the path in the `included` list, same as SwiftLint.
